[sources.chat_group]
type = "foochat"
token = "foochat-token"
group_id = "group-123"
include = ["admin", "owner"]

[destinations.code_team]
type = "foocode"
api_key = "foocode-api-key"
team_name = "team-abc"
role = "member"

[[syncs]]
source = "chat_group"
destination = "code_team"
